---
apiVersion: v1
kind: Service
metadata:
  name: bootstrap
  namespace: default
spec:
  ports:
  - port: 9092
  selector:
    app: kafka
---
# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: default
spec:
  ports:
  - port: 9092
  # [podname].broker.default.svc.cluster.local
  clusterIP: None
  selector:
    app: kafka
